spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/fly?characterEncoding=utf-8&useSSL=false
#    jdbc:mysql://10.122.30.102:3306/bank_collection?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
    validation-query: SELECT 1
    validation-query-timeout: 5000
    test-on-borrow: true
    test-on-connect: true
#    hikari:
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
#        maximumPoolSize: 30
#        minimumIdle: 5
#        autoCommit: true
#        useLocalSessionState: true
#        useLocalTransactionState: true
#        rewriteBatchedStatements: true
#        cacheResultSetMetadata: true
#        cacheServerConfiguration: true
#        elideSetAutoCommits: true
#        connectionTestQuery: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update  #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  data:
    mongodb:
      uri: mongodb://localhost:27017/lvzheng
    elasticsearch:
      # 配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      cluster-nodes: localhost:9300
      # 默认为elasticsearch
      cluster-name: lvzheng
      repositories:
        enabled: true
  rabbitmq:
    password: guest
    port: 5672
    host: 127.0.0.1
    username: guest
  kafka:
    bootstrap-servers: 10.122.45.154:9092,10.122.45.155:9092
    consumer:
      group-id: lvzheng
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      earliest 当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费
#      latest  当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据
#      none topic各分区都存在已提交的offset时，从offset后开始消费；只要有一个分区不存在已提交的offset，则抛出异常
      auto-offset-reset: latest
      enable-auto-commit: true
#    如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
#      auto-commit-interval: 100ms
#     设置每次拉取最大10条
      max-poll-records: 10
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 524288
      retries: 3
      batch-size: 65536
    template:
      default-topic: lvzheng

#  security:
#    user:
#      name: admin
#      password: admin
#  application:
#    name: lvzheng-service
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8888/eureka/
      

server:
  port: 9999

#logging:
#  level:
#    com.itmuch.cloud.feign.UserFeignClient: DEBUG


jdvop: http://bizapi.jd.com
grant_type: access_token
client_id: PGLjA7gNCfUsxryKD3SD
client_secret: w4lcjqtHFCUqHvluT8eZ
username: 联想百应VOP
password: lianxiangbaiying666

topic: lvzheng

