spring:
  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/fly?characterEncoding=utf-8&useSSL=false
    validation-query: SELECT 1
    validation-query-timeout: 5000
    test-on-borrow: true
    test-on-connect: true
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maximumPoolSize: 30
        minimumIdle: 5
        autoCommit: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        connectionTestQuery: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true    
    hibernate:  
      #ddl-auto: update 
      naming:  
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy  
#  security:
#    user:
#      name: admin
#      password: admin
  application:
    name: lvzheng-service
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/ 
      

server:
  port: 9999

logging:
  level:
    com.itmuch.cloud.feign.UserFeignClient: DEBUG



